Feat/add incentives properties
vtex-sites/storeframework.store pull request #47
Opened 2022-04-08 14:46 UTC by israelswf

## What's the purpose of this pull request?

<em>Considering the context, what is the problem we'll solve? Where in VTEX's big picture our issue fits in? Write a tweet about the context and the problem itself.</em>

## How does it work?

<em>Tell us the role of the new feature, or component, in its context.</em>

## How to test it?

<em>Describe the steps with bullet points. Is there any external reference, link, or example?</em>

## References

<em>Spread the knowledge: is this any content you used to create this PR that is worth sharing?</em>

<em>Extra tip: add references to related issues or mention people important to this PR may be good for the documentation and reviewing process</em>

## Checklist

<em>You may erase this after checking them all ;)</em>

- [] CHANGELOG entry added

2022-04-08 20:54 UTC, filipewl approved these changes
LGTM!

2022-04-08 20:54 UTC, filipewl commented on CHANGELOG.md
> +- IncentivesHeader is now integrated with CMS
Just to separate more from the _Changed_ section below.

```suggestion
- IncentivesHeader is now integrated with CMS

```

2022-04-08 20:54 UTC, filipewl commented on src/components/sections/Incentives/IncentivesHeader.tsx
> +  classes?: string
Maybe we can remove this one if it's not being used.
```suggestion
```

2022-04-09 15:08 UTC, tlgimenes requested changes
Please, don't do these changes in here. Do these changes on base.store and them rebase it in here. This way we keep changes to a minimum, with the only difference being the actual CMS integration, not really the components.

To avoid re-doing this work, you can also backport it to base.store

However, awesome work you did, for me it's a LGTM 🎉

2022-04-11 22:16 UTC, merged