Feat/add alert cms
vtex-sites/storeframework.store pull request #49
Opened 2022-05-11 18:03 UTC by israelswf

## What's the purpose of this pull request?

<em>Considering the context, what is the problem we'll solve? Where in VTEX's big picture our issue fits in? Write a tweet about the context and the problem itself.</em>

## How does it work?

<em>Tell us the role of the new feature, or component, in its context.</em>

## How to test it?

<em>Describe the steps with bullet points. Is there any external reference, link, or example?</em>

## References

<em>Spread the knowledge: is this any content you used to create this PR that is worth sharing?</em>

<em>Extra tip: add references to related issues or mention people important to this PR may be good for the documentation and reviewing process</em>

## Checklist

<em>You may erase this after checking them all ;)</em>

- [] CHANGELOG entry added

2022-05-12 16:23 UTC, filipewl commented on src/Layout.tsx
> -      <main>{children}</main>
We need this `main` tag somewhere or axe accessibility tests will complain about the page missing landmarks: https://dequeuniversity.com/rules/axe/4.4/region?application=AxeChrome

2022-05-12 18:15 UTC, israelswf commented on src/Layout.tsx
> -      <main>{children}</main>
Ouch! Have no idea why I've removed that. Fixing that now.

2022-05-13 18:16 UTC, filipewl approved these changes
Looks good to me! Thanks to the detailed instructions on how to test with the CMS, I was able to test it myself.
![image](https://user-images.githubusercontent.com/381395/168343358-8878c1ed-074c-4bff-a156-2748132efbe1.png)

I found it easier to [review without the white space](https://github.com/vtex-sites/storeframework.store/pull/49/files?w=1) changes.

2022-05-13 18:16 UTC, filipewl commented on src/components/RenderCMS.tsx
> +          return <></>
We had to change this because the app got stuck in a loop?

Should we add `Alert` to the `COMPONENTS` object above, or it doesn't make sense?
<img width="618" alt="CleanShot 2022-05-13 at 15 13 41@2x" src="https://user-images.githubusercontent.com/381395/168343087-6f09e4fa-1d00-4cc0-b63e-f75ec11aa986.png">

2022-05-13 19:05 UTC, israelswf commented on src/components/RenderCMS.tsx
> +          return <></>
Exactly, @filipewl. The app was looping every time the error was thrown. I could not add the `Alert` to `COMPONENTS`, otherwise it would be rendered below `Navbar,` along with the other components: 
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/10616243/168372517-8f63a5ad-eb7b-4db1-8ab6-4afbbad46fe6.png">

2022-05-13 21:13 UTC, danzanzini requested changes
Good job!

One thing to look at: This PR changed the behavior of having the alert on all pages. Shouldn't we make the changes to accept the data from the cms and still have the same behavior?

I'm requesting a change due to the behavior I show on the code.

2022-05-13 21:13 UTC, danzanzini commented on src/pages/index.tsx
> +      )}
At the preview, the alert appears even if no data provided:

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/8497187/168390258-68a76868-ee88-48c5-821f-24a9567d207f.png">

2022-05-16 17:16 UTC, israelswf commented on src/pages/index.tsx
> +      )}
Dan, the reason this weird `Alert` is showing up is because there is dirt in the database with the previous json format for the `Alert`. `text` was replaced by `content`, thats why we see this `Alert` 'empty'. But once everything is merged with `master`, this should disappear.

<img width="857" alt="image" src="https://user-images.githubusercontent.com/10616243/168647177-7e905031-eb2f-46a0-9aa5-5c8340b68e46.png">

2022-05-16 17:32 UTC, israelswf commented on src/pages/index.tsx
> +      )}
About having the `Alert` in all pages, I totally agree it should appear in all the pages, just checking the effort to achieve this.

2022-05-18 19:19 UTC, israelswf commented
This PR was replace for this cleaner PR (#50) PR, with a better approach.

2022-05-18 19:19 UTC, closed without merging